force_compliance:
    controller:
        package: dynamixel_controllers
        module: force_compliance_controller
        type: ForceComplianceController
    joint_name: force_compliance
    joint_speed: 0.1
    motor:
        id: 0
        init: 896
        min: 0
        max: 4096
