tilt_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: tilt_joint
    joint_speed: 0.15
    motor:
        id: 4
        init: 2500
        min: 1500
        max: 3500
wrist_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: wrist_joint
    joint_speed: 0.3
    motor:
        id: 5
        init: 0
        min: 0
        max: 4096

fingers_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller_dual_motor
        type: JointPositionControllerDual
    joint_name: fingers_motor
    joint_speed: 0.30
    motor_master:
        id: 6
        init: 0
        min: -2047
        max: 2047
    motor_slave:
        id: 7
