q3_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: q3_joint
    joint_speed: 0.3
    motor:
        id: 5
        init: 0
        min: 0
        max: 4096
tilt_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: tilt_joint
    joint_speed: 0.15
    motor:
        id: 4
        init: 2500
        min: 1500
        max: 3500
wrist_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: wrist_joint
    joint_speed: 0.3
    motor:
        id: 5
        init: 0
        min: 0
        max: 4096

