joint_1:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_1
    joint_speed: 0.2
    motor:
        id: 0
        init: 1024
        min: 0
        max: 4096
joint_2:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_2
    joint_speed: 0.2
    motor:
        id: 1
        init: 1992
        min: 0
        max: 4096
joint_3:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_3
    joint_speed: 0.3
    motor:
        id: 2
        init: 2688
        min: 0
        max: 4096
joint_4:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_4
    joint_speed: 0.2
    motor:
        id: 3
        init: 2240
        min: 0
        max: 4096
joint_5:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_5
    joint_speed: 0.2
    motor:
        id: 4
        init: 2496
        min: 1500
        max: 3500
joint_6:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_6
    joint_speed: 0.2
    motor:
        id: 5
        init: 3840
        min: 0
        max: 4096
finger_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller_dual_motor
        type: JointPositionControllerDual
    joint_name: dual_motor
    joint_speed: 0.1
    motor_master:
        id: 6
        init: 0
        min: 2047
        max: 2850
    motor_slave:
        id: 7
